baseurl: https://hidehic0.github.io
languageCode: ja
DefaultContentLanguage: ja
title: hidehic0のブログ
theme:
  - hugo-theme-stack
  - hugo-notice
disqusShortname: hugo-theme-stack
permalinks:
  post: /p/:slug/
  page: /:slug/
params:
  favicon: "/blog/img/avatar.png"
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  dateFormat:
    published: 2006年 1月 02日
    lastUpdated: 2006年 1月 02日
  sidebar:
    subtitle: "中2 AtCoder緑/緑 Paiza S"
    avatar:
      local: false
      enabled: true
      src: https://github.com/hidehic0.png
  article:
    math: true
    toc: true
    readingTime: false
    comments:
      enabled: true
      provider: utterances
      utterances:
        repo: hidehic0/blog
        issueTerm: pathname
        label: Comment
  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc
  defaultImage:
  opengraph:
    enabled: true
    local: false
    src: https://github.com/hidehic0.png
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        newTab: false
        icon: home
  social:
    - identifier: github
      name: Github
      url: https://github.com/hidehic0/
      params:
        icon: brand-github
related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200
markup:
  goldmark:
    renderer:
      unsafe: true
buildFuture: false
enableRobotsTXT: true
